### ISSUE TITLE
Socket endpoint in management api v2

### ISSUE THREAD

**Issue by brianhulick** [auth0-extensions/auth0-ldap-connector-health-monitor#4]
I don't see any reference in the Management API v2 documentation of the socket endpoint used in v1 here:
`https://${ctx.data.AUTH0_DOMAIN}/api/connections/${ctx.data.connection}/socket;`

Is there an equivalent endpoint we can use in v2?

**Comment by ademartini** [comment]
Hi Brian, this is the endpoint in API V2: https://auth0.com/docs/api/management/v2#!/Connections/get_status

For further referenc: https://auth0.com/docs/api/management-api-changes-v1-to-v2
